services:
  # Next.js Frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - NEXT_PUBLIC_MAPBOX_TOKEN=${NEXT_PUBLIC_MAPBOX_TOKEN}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
    depends_on:
      - backend

  # Flask Backend
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/static/uploads:/app/static/uploads
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/delivery_db
      - MAPBOX_ACCESS_TOKEN=${MAPBOX_ACCESS_TOKEN}
    depends_on:
      db:
        condition: "service_healthy"
    command: >
      sh -c "python db_init.py && gunicorn --bind 0.0.0.0:5000 app:app"

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=delivery_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # This command runs inside the DB container to see if it's accepting connections
      test: ["CMD-SHELL", "pg_isready -U user -d delivery_db"]
      interval: 5s # Check every 5 seconds
      timeout: 5s # If the check takes > 5s, it's a fail
      retries: 5 # Try 5 times before giving up
      start_period: 10s # Give it 10s to boot before starting checks

volumes:
  postgres_data:
